Deploy with docker-compose

diff --git a/cloudformation-openvidu/CF-OpenVidu-TEMPLATE.yaml b/cloudformation-openvidu/CF-OpenVidu-TEMPLATE.yaml
--- a/cloudformation-openvidu/CF-OpenVidu-TEMPLATE.yaml
+++ b/cloudformation-openvidu/CF-OpenVidu-TEMPLATE.yaml
@@ -409,13 +409,50 @@ Resources:
               mode: '000400'
               owner: root
               group: root
-            '/usr/local/bin/installAnsible.sh':
+              '/usr/local/bin/check_app_ready.sh':
+                content: |
+                  #!/bin/bash 
+
+                  sleep 1m
+
+                  while true
+                  do 
+                    HTTP_STATUS=$(curl -Ik https://localhost:{{ openvidu_server_port }} | head -n1 | awk '{print $2}')
+                    if [ $HTTP_STATUS == 401 ]; then
+                      break
+                    fi
+                    sleep 1
+                  done
+                mode: "000755"
+                owner: "root"
+                group: "root"
+            '/usr/local/bin/installDockerAndDockerCompose.sh':
               content: |
-                #!/bin/bash
-                apt-add-repository -y ppa:ansible/ansible
-                apt-get update && apt-get install -y ansible
-                ansible-galaxy install -p /etc/ansible/roles geerlingguy.docker
-                ansible-galaxy install -p /etc/ansible/roles geerlingguy.mysql
+              #!/bin/bash              
+              # Install Docker
+              apt-get update && apt-get install -y \
+                  apt-transport-https \
+                  ca-certificates \
+                  curl \
+                  gnupg-agent \
+                  software-properties-common
+
+              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
+              apt-key fingerprint 0EBFCD88
+              add-apt-repository \
+                "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
+                $(lsb_release -cs) \
+                stable"
+
+              apt-get update && apt-get install -y \
+                  docker-ce \
+                  docker-ce-cli \
+                  containerd.io
+
+              # Install docker-compose
+              curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+              chmod +x /usr/local/bin/docker-compose
+              ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
               mode: "000755"
               owner: "root"
               group: "root"
@@ -428,46 +465,25 @@ Resources:
               mode: "000755"
               owner: "root"
               group: "root"
-            '/usr/local/bin/getPublicInfo.sh':
-              content: |
-                #!/bin/bash
-                WORKINGDIR=/usr/src/openvidu/cloudformation-openvidu
-                PIP=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)
-                PublicHostname=$(curl http://169.254.169.254/latest/meta-data/public-hostname)
-                sed -i "s/AWS_EIP/$PIP/" $WORKINGDIR/group_vars/all
-                sed -i "s/AWS_PUBLIC_HOSTNAME/$PublicHostname/" $WORKINGDIR/group_vars/all
-              mode: "000755"
-              owner: "root"
-              group: "root"
             '/usr/local/bin/feedGroupVars.sh':
               content: !Sub |
                 #!/bin/bash -x
                 WORKINGDIR=/usr/src/openvidu/cloudformation-openvidu
                 OPENVIDU_VERSION=@OV_V@
-                OPENVIDU_DEMOS_VERSION=@OVD_V@
-                OPENVIDU_CALL_VERSION=@OVC_V@
-                sed -i "s/OPENVIDU_VERSION/$OPENVIDU_VERSION/" $WORKINGDIR/group_vars/all
-                sed -i "s/DEMOS_VERSION/$OPENVIDU_DEMOS_VERSION/" $WORKINGDIR/group_vars/all
-                sed -i "s/OVC_VERSION/$OPENVIDU_CALL_VERSION/" $WORKINGDIR/group_vars/all
-                sed -i "s/WANTDEMOS/${WantToDeployDemos}/" $WORKINGDIR/group_vars/all
-                sed -i "s/whichcert: selfsigned/whichcert: ${WhichCert}/" $WORKINGDIR/group_vars/all
-                sed -i "s/DOMAIN_NAME/${MyDomainName}/" $WORKINGDIR/group_vars/all
-                sed -i "s/LETSENCRYPT_EMAIL/${LetsEncryptEmail}/" $WORKINGDIR/group_vars/all
-                sed -i "s/MY_SECRET/${OpenViduSecret}/" $WORKINGDIR/group_vars/all
-                sed -i "s/run_ec2: false/run_ec2: true/" $WORKINGDIR/group_vars/all
-                sed -i "s/allowsendinfo: true/allowsendinfo: ${WantToSendInfo}/" $WORKINGDIR/group_vars/all
-                sed -i "s/FREEHTTPACCESTORECORDINGVIDEOS/${FreeHTTPAccesToRecordingVideos}/" $WORKINGDIR/group_vars/all
-                sed -i "s/OPENVIDURECORDINGNOTIFICATION/${OpenviduRecordingNotification}/" $WORKINGDIR/group_vars/all
-                sed -i "s/OPENVIDURECORDINGTIMEOUT/${OpenViduRecordingTimeOut}/" $WORKINGDIR/group_vars/all
-                sed -i "s/OPENVIDUSTREAMSVIDEOMAX-RECV-BANDWIDTH/${OpenviduStreamsVideoMaxRecvBandwidth}/" $WORKINGDIR/group_vars/all
-                sed -i "s/OPENVIDUSTREAMSVIDEOMIN-RECV-BANDWIDTH/${OpenviduStreamsVideoMinRecvBandwidth}/" $WORKINGDIR/group_vars/all
-                sed -i "s/OPENVIDUSTREAMSVIDEOMAX-SEND-BANDWIDTH/${OpenviduStreamsVideoMaxSendBandwidth}/" $WORKINGDIR/group_vars/all
-                sed -i "s/OPENVIDUSTREAMSVIDEOMIN-SEND-BANDWIDTH/${OpenviduStreamsVideoMinSendBandwidth}/" $WORKINGDIR/group_vars/all
-                sed -i "s/WEBHOOK_ENABLED/${OpenViduWebhook}/" $WORKINGDIR/group_vars/all
-                sed -i "s#WEBHOOK_ENDPOINT#${OpenViduWebhookEndpoint}#" $WORKINGDIR/group_vars/all
-                sed -i "s/WEBHOOK_HEADERS/${OpenViduWebhookHeaders}/" $WORKINGDIR/group_vars/all
-                sed -i "s/WEBHOOK_EVENTS/${OpenViduWebhookEvents}/" $WORKINGDIR/group_vars/all
-                sed -i "s/OPENVIDU_CDR/${OpenviduCDREnable}/" $WORKINGDIR/group_vars/all
+
+                sed -i "s/OPENVIDU_VERSION/$OPENVIDU_VERSION/" $WORKINGDIR/docker-compose/.env
+                sed -i "s/WANTDEMOS/${WantToDeployDemos}/" $WORKINGDIR/docker-compose/.env
+                sed -i "s/whichcert: selfsigned/whichcert: ${WhichCert}/" $WORKINGDIR/docker-compose/.env
+                sed -i "s/LETSENCRYPT_EMAIL/${LetsEncryptEmail}/" $WORKINGDIR/docker-compose/.env
+                sed -i "s/MY_SECRET/${OpenViduSecret}/" $WORKINGDIR/docker-compose/.env
+                
+                if [ "${WhichCert}" == "letsencrypt" || "${WhichCert}" == "owncert" ]; then
+                    sed -i "s/DOMAIN_NAME/${MyDomainName}/" $WORKINGDIR/docker-compose/.env
+                else
+                    PublicHostname=$(curl http://169.254.169.254/latest/meta-data/public-hostname)
+                
+                    sed -i "s/DOMAIN_NAME/${PublicHostname}/" $WORKINGDIR/docker-compose/.env
+                fi
               mode: "000755"
               owner: "root"
               group: "root"
@@ -475,8 +491,8 @@ Resources:
               content: !Sub |
                 #!/bin/bash -x
                 WORKINGDIR=/usr/src/openvidu/cloudformation-openvidu
-                wget -O $WORKINGDIR/roles/nginx/files/nginx.crt ${OwnCertCRT}
-                wget -O $WORKINGDIR/roles/nginx/files/nginx.key ${OwnCertKEY}
+                wget -O $WORKINGDIR/docker-compose/owncert/certificate.crt ${OwnCertCRT}
+                wget -O $WORKINGDIR/docker-compose/owncert/certificate.key ${OwnCertKEY}
               mode: "000755"
               owner: "root"
               group: "root"
@@ -519,18 +535,15 @@ Resources:
 
           cfn-init --region ${AWS::Region} --stack ${AWS::StackId} --resource OpenviduServer
 
-          /usr/local/bin/installAnsible.sh || { echo "[Openvidu] Can't install ansible"; exit 1; }
+          /usr/local/bin/installDockerAndDockerCompose.sh || { echo "[Openvidu] Can't install docker or docker-compose"; exit 1; }
           /usr/local/bin/cloneRepo.sh || { echo "[Openvidu] Can't clone the repo"; exit 1; }
-          /usr/local/bin/getPublicInfo.sh || { echo "[Openvidu] Network problem"; exit 1; }
           /usr/local/bin/feedGroupVars.sh || { echo "[Openvidu] Parameters incorrect/insufficient"; exit 1; }
           if [ "${WhichCert}" == "owncert" ]; then
             /usr/local/bin/buildCerts.sh || { echo "[Openvidu] error with the certificate files"; exit 1; }
           fi
-          source /home/ubuntu/.bashrc
-          export HOME=/home/ubuntu
 
-          pushd /usr/src/openvidu/cloudformation-openvidu
-          ansible-playbook -i "localhost," -c local play.yml
+          pushd /usr/src/openvidu/cloudformation-openvidu/docker-compose
+          docker-compose up -d
           popd
 
           # Wait for the app
